### ISSUE TITLE
Changed "λ"  to "?"

### ISSUE THREAD

**Issue by AndreyUtka** [bliker/cmder#104]
When I go to powershell, symbol "λ" changed to "?".
![2013-12-30_1837](https://f.cloud.github.com/assets/1304912/1823052/579f727e-7171-11e3-920e-0c6e4f36db1a.png)

**Comment by f3yisayo** [comment]
@bravelee I also wanted to have this instead of the Lambda, I did some digging and found a Lua script in `CMDER\config\` 

1. Open the `prompt.lua` script in the path above in an editor.
2. On the second line, just replace `λ` with `$` and save, have fun.

**Comment by haoxi911** [comment]
@f3yisayo I didn't see the prompt.lua script in the latest version, is there another way to replace `λ` with `$`? I like the tool but it looks weird to type something after `λ`.

**Comment by Ov4ts** [comment]
@haoxi911 I found a new way, go to ~cmder\vendor, open clink.lua, line 44, change to (lambda = "$") and save. Done.

**Comment by haoxi911** [comment]
@Ov4ts It works great. Thank You!

**Comment by taichushouwang** [comment]
@Ov4ts What you say make cmd work, but for the powershell, it's still λ

**Comment by mataps** [comment]
to change for λ replace the ff files:
`cmder\vendor\clink.lua`  
`cmder\vendor\profile.ps1`  
`cmder\vendor\git-for-windows\etc\profile.d\git-prompt.sh`

**Comment by smltrs0** [comment]
UPDATED

CMDER\config\_powerline_config.lua

--
plc_prompt_lambSymbol = "NEW SIMBOL"

**Comment by taowaaCool** [comment]
update:
edit .../cmder/config/cmder_prompt_config.lua
...
prompt_lambSymbol = "NEW Symbol"
...
