### ISSUE TITLE
"The system cannot find the path specified"

### ISSUE THREAD

**Issue by tomasgonz** [bliker/cmder#121]
I have cmder in a folder in dropbox. Although it works fine in windows 7, when I try to execute it in my computer at home (windows 8,1), the message "the system cannot find the path specified" appears once. Moreover, the same message appears after executing a command.

**Comment by meeglos** [comment]
I followed  @FreaKzero's  comment on my regedit. What I actually found in the autorun entry was this:

> "C:\Program Files (x86)\clink\0.4.5\clink" inject --profile "~\clink"

Now the annoying error message is gone.

**Comment by vrushabhk13** [comment]
No need to change anything in the regedit or anything, just go to the properties of the zip file & choose file explorer to unzip the file & unzip it with that. It didn't work with the WinRar but, File Explorer did it for me. I hope it helps. :)

**Comment by ransur0t** [comment]
Similiar to @meeglos, my issue was related to clink, yet uses the same registry fix.  Thanks @FreaKzero!

For context, the reason the registry key was an issue is due to some install/uninstall/reinstall attempts I made while trying to debug an issue with clink environmental aliases not working after Windows 10 Creator update earlier this year.

I eventually ended up leaving clink uninstalled because, while tab completion worked, the aliases themselves did not execute (command not recognized, etc).

If I had ran a utility like ccleaner after the debugging efforts, I suspect it would have removed the offending key for me.  :)

Regards,

**Comment by RamiSingh** [comment]
> Hi all again, i found the Problem and i want to share that big bullsh....
> 
> Since i can remember i use Ansicon for an colored cmd.exe (PHPUnit...) in work and never had Problems or anything with it - not with Vista, not with XP and not with 7. Even now i have cmder AND Ansicon installed on my Work machine which is an Windows 7 machine - never had that strange errors.
> 
> Well ... on my private coding machine with Windows 8 - ansicon dont play nice with other Programs - i had the exact same Problem with the Sublime Text - Sublimerge Plugin and i began to investigate.
> 
> When you run into this "The system cannot find the path specified" Problem, have Windows 8 and ANSICON is installed - Delete the Ansicon Entries in the Registry there:
> 
> HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
> 
> That solved all my Problems.
> Thanks mate.

**Comment by HBenzaoui** [comment]
> Hi all again, i found the Problem and i want to share that big bullsh....
> 
> Since i can remember i use Ansicon for an colored cmd.exe (PHPUnit...) in work and never had Problems or anything with it - not with Vista, not with XP and not with 7. Even now i have cmder AND Ansicon installed on my Work machine which is an Windows 7 machine - never had that strange errors.
> 
> Well ... on my private coding machine with Windows 8 - ansicon dont play nice with other Programs - i had the exact same Problem with the Sublime Text - Sublimerge Plugin and i began to investigate.
> 
> When you run into this "The system cannot find the path specified" Problem, have Windows 8 and ANSICON is installed - Delete the Ansicon Entries in the Registry there:
> 
> HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
> 
> That solved all my Problems.
> Cheers!

Thanks dude, what a life saver ;)

**Comment by tek-shinobi** [comment]
Had the same issue. Whenever I would run cmder, it would display "The system cannot find the path specified".

Tried everything mentioned on this page. Nothing worked. Finally found a clue "[here](https://github.com/cmderdev/cmder/issues/2049)". But since in my case it worked differently, am describing it here.

**Firstly,** I had to setup `cmder_root` environment variable separately. It points to the location of cmder on my computer.

**Secondly:** In cmder goto: Settings->Integration->ComSpec
Go all the way down:
![cmder](https://user-images.githubusercontent.com/43358610/70787272-c16b4c80-1da7-11ea-8874-bee5c77facda.png)

 I had to click on "Register ConEmu Autorun" and save settings and then the error went away.

What I realized was that it was unable to launch vendor/init.bat on start of cmder console. If above does not solve your issue, try opening the vanilla console (cmd.exe .. the DOS console) and try to launch the following command and see what you get:
$C:\cmder\vendor\init.bat 

and then take it from there.

**Comment by hossainrkb** [comment]
> Hi all again, i found the Problem and i want to share that big bullsh....
> 
> Since i can remember i use Ansicon for an colored cmd.exe (PHPUnit...) in work and never had Problems or anything with it - not with Vista, not with XP and not with 7. Even now i have cmder AND Ansicon installed on my Work machine which is an Windows 7 machine - never had that strange errors.
> 
> Well ... on my private coding machine with Windows 8 - ansicon dont play nice with other Programs - i had the exact same Problem with the Sublime Text - Sublimerge Plugin and i began to investigate.
> 
> When you run into this "The system cannot find the path specified" Problem, have Windows 8 and ANSICON is installed - Delete the Ansicon Entries in the Registry there:
> 
> HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
> 
> That solved all my Problems.
> Cheers!

a big round of applause for you bro !

**Comment by keocra** [comment]
Hi everyone,
I observed the same issue but found a different reason. In "vendor/lib/lib_path.cmd" (https://github.com/cmderdev/cmder/blob/bc7984769ce32c7b33d322266ac52900d57f95d6/vendor/lib/lib_path.cmd#L171) is a call which tries to identify if the folder path given to the script exists. If not, it produces the message "The system cannot find the path specified.". In my case some other script tries to add ...Git\mingw64\bin\usr\bin which does not exist on my system. As a quick fix I created the expected folder.

**Comment by jiashie** [comment]
> Hi everyone,
> I observed the same issue but found a different reason. In "vendor/lib/lib_path.cmd" (
> 
> https://github.com/cmderdev/cmder/blob/bc7984769ce32c7b33d322266ac52900d57f95d6/vendor/lib/lib_path.cmd#L171
> 
> ) is a call which tries to identify if the folder path given to the script exists. If not, it produces the message "The system cannot find the path specified.". In my case some other script tries to add ...Git\mingw64\bin\usr\bin which does not exist on my system. As a quick fix I created the expected folder.

same case! worked for me.

**Comment by daxgames** [comment]
@keocra @jiashie what git do you have installed?  Is it Git for Windows? 32 or 64bit?

I can see this happening if you have Cmder mini with 32bit Git for Windows installed.  If you were using 64bit Git for Windows the folder would exist.

**Comment by zetaontherocks** [comment]
Hi Everyone,

I'm on windows 10 having the same issue, 

Everytime I type "cd Desktop" I get the "System cannot find the path specified" each time,

Any suggestions,

**Comment by daxgames** [comment]
@zetaontherocks Is `Desktop` folder in the current folder?  `dir` output or `cd /d %userprofile%\Desktop`

**Comment by zetaontherocks** [comment]
> @zetaontherocks Is `Desktop` folder in the current folder? `dir` output or `cd /d %userprofile%\Desktop`

No, it's not. I'm having success with cd %userprofile%/Desktop . What shall I do ? I am a bit confused and embarrased, ha.

**Comment by gancena** [comment]
> > @zetaontherocks Is `Desktop` folder in the current folder? `dir` output or `cd /d %userprofile%\Desktop`
> 
> No, it's not. I'm having success with cd %userprofile%/Desktop . What shall I do ? I am a bit confused and embarrased, ha.

@zetaontherocks you can only cd into folders with `cd _folder_` if you're in the same parent folder. You can tell what folder you're in with `pwd` then `dir` to list all the files and directories inside the directory that you're currently in.

**Comment by AsrorKhans** [comment]
I have the same problem with Windows 11. I installed last version cmder. But I cannot work with him. Error  "The system cannot find the path specified".  Someone can help me?

**Comment by hesammoosapour** [comment]
I deleted the Autorun in here:
_Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor_
I also added CMDER_ROOT for my user and in path as well:
![image](https://github.com/cmderdev/cmder/assets/18083007/8d918f97-2046-4112-9f84-939ce150e297)

But it still shows the same error!
Please tell me how to fix it.🙏

**Comment by marwandev-ps** [comment]
> Hi everyone, I observed the same issue but found a different reason. In "vendor/lib/lib_path.cmd" (
> 
> https://github.com/cmderdev/cmder/blob/bc7984769ce32c7b33d322266ac52900d57f95d6/vendor/lib/lib_path.cmd#L171
> 
> ) is a call which tries to identify if the folder path given to the script exists. If not, it produces the message "The system cannot find the path specified.". In my case some other script tries to add ...Git\mingw64\bin\usr\bin which does not exist on my system. As a quick fix I created the expected folder.

I tried and it worked, thx so much
