### ISSUE TITLE
Lamba prompt and git status scripts not running

### ISSUE THREAD

**Issue by josh-nz** [bliker/cmder#126]
Hi,

I've tried both the light and full versions with the same behaviour.
The git status prompt reads {git} and the lamba prompt reads {lamb}.

Refer to this image:
![2014-01-24_16h08_58](https://f.cloud.github.com/assets/414204/2027361/3be4e882-88b1-11e3-9061-20d9b2259802.png)

I've tried to trace the loading sequence. It seems the launcher just calls vendor\conemu-maximus5\ConEmu.exe with some args for the icon, title, and the config file config\ConEmu.xml

Somehow I believe vendor\init.bat gets called, which sets the prompt with the {git} and {lamb} placeholders then loads clink using the profile in the config folder.

The config folder has git and lamba lua files, which I understand to be extension points for clink, having checked the docs. They appear to be named and written correctly. These scripts should replace the placeholders accordingly, but do not do so for me.

Any suggestions?

**Comment by mirceanis** [comment]
I solved the {git} & {lamb} bug by upgrading the clink version to 0.4.4
( overwriting the /vendor/clink folder contents )
