### ISSUE TITLE
Git Credential Cache

### ISSUE THREAD

**Issue by patricksnape** [bliker/cmder#184]
Not sure if this is an issue with msysgit or not, but it would be great if cmder could include a [git credential cache](http://gitcredentialstore.codeplex.com/). This is very useful if you want to use HTTPS repositories on Github. At the moment I always have to download cmder, then download the credential store and install it manually. Including this be default would be awesome!

**Comment by r3Fuze** [comment]
A little late here.. I looked into implementing this, but I don't think it will be necessary.
With Git 1.7.10 or newer you can use the default Windows credential manager.
`$ git config --global credential.helper wincred` to enable.
Read more here https://help.github.com/articles/caching-your-github-password-in-git/#platform-windows

Maybe make Cmder do this automatically? It's a lot simpler and doesn't require any additional files.

**Comment by MartiUK** [comment]
I see, I guess we can put it in the docs.
