### ISSUE TITLE
command autocompletion not working

### ISSUE THREAD

**Issue by grirgz** [bliker/cmder#218]
Hi,

I just installed cmder on my computer (Windows 7), everything seems working nice, except autocompletion of commands, if I type "notepa" then [tab] nothing happens. If I type notepad[Enter] notepad is launched, so the path seems corect. Files and directories are completed without problem.

I tried with mini and normal version, both have the problem

Thanks

**Comment by valueforvalue** [comment]
@vladimir-kotikov Thanks this saved me some frustration.

**Comment by eliveikis** [comment]
Should auto-complete with tabs work with `alias` commands? I thought they used to but perhaps I am mistaken.

**Comment by AlanTrudor** [comment]
Hey I am having this same problem but there is no settings file in v1.3.18.1106, could someone please help me resolve it :)
