### ISSUE TITLE
"Create new console" option opens a new tab with cmd's icon instead of Cmder's

### ISSUE THREAD

**Issue by dcominottim** [bliker/cmder#255]
![cmder](https://cloud.githubusercontent.com/assets/4914233/4145292/7ccf1832-33f5-11e4-9693-f6b43261ee41.jpg)

**Comment by HaykoKoryun** [comment]
+1 I hate the ugly cmd icon and would love all of them to be the same as cmder

**Comment by MartiUK** [comment]
This will be fixed in the next version, icons were being excluded in the pack script. See https://github.com/bliker/cmder/commit/e95127268ed71f2151356c72d31852b3fe4451fa
