### ISSUE TITLE
Git and lamb macro/symbols not expanded in Windows 10 preview

### ISSUE THREAD

**Issue by vitaminj** [bliker/cmder#279]
Just a heads-up that the changes MS have made to cmd.exe seem to have clobbered the expansion of git and lamb into the branch name and the lambda symbol respectively. I guess this requires a fix in clink or something else further down, but I'm not sure exactly what component(s) are responsible for this functionality.

**Comment by MartiUK** [comment]
Should be fixed in 1.2 release.

**Comment by luisrudge** [comment]
@MartiUK when is that coming out?
