### ISSUE TITLE
{lamb} instead of lambda sign (possibly a UTF-8 problem?)

### ISSUE THREAD

**Issue by jszym** [bliker/cmder#322]
![2014-11-17_23-25-20](https://cloud.githubusercontent.com/assets/1421301/5082580/08910006-6eb1-11e4-8569-e84991e44a80.png)

Instead of getting a pretty lambda sign, I get {lamb} as my prompt. :disappointed:

**Comment by tengwar** [comment]
I have the same problem when running Cmder as root, but everything is fine when I run it as me. In a root tab I get a warning that translates to
>System can't find the given path.
>File not found - C:\Users\User\Copy\random\config\aliases

I have it in a directory like "C:\Users\User\Copy\random stuff", so it looks like spaces aren't handled properly in root mode.

**Comment by K900** [comment]
Same issue on Windows 10 Technical Preview is solved by upgrading to Clink 0.4.3

**Comment by CoreyH** [comment]
Windows 10 RTM I am having this issue. I installed/upgraded to Clink 0.4.3 via Chocolatey and I am still stuck with {lamb}

**Comment by ClementParis016** [comment]
Same problem for me on latest Windows 10, I have no other Clink installed next to the one included with Cmder

**Comment by sekai92id** [comment]
any solution?

**Comment by MartiUK** [comment]
Download the latest pre-release, do not install anything from chocolatey.

**Comment by Jayflux** [comment]
i downloaded the latest version of clink and still have this issue 
(using 1.2.9)

**Comment by MartiUK** [comment]
Clink is included with cmder already.

**Comment by kowsheek** [comment]
The latest prerelease didn't fix the issue.

**Comment by bittin** [comment]
yeah got that problem in Windows 10 on my work computer like 2 days ago aswell, when opening up a new cmd.exe :(

**Comment by Jayflux** [comment]
@MartiUK people still having issues, maybe this should be re-opened?

**Comment by sekai92id** [comment]
i fix the issue by uninstall clink on my PC before i use cmder

**Comment by kowsheek** [comment]
I fixed it by installing a updated version to the clink folder in cmder.

**Comment by Jayflux** [comment]
I also did the above to fix it, the pre-release didn't solve it for me
