### ISSUE TITLE
set ~ to home directory 

### ISSUE THREAD

**Issue by jebaird** [bliker/cmder#327]
Maybe this is easy to do, but how do I set `~` to the current users home directory?

**Comment by vladimir-kotikov** [comment]
`alias ~=cd /d ^%USERPROFILE^%` will help you :)

**Comment by vladimir-kotikov** [comment]
@MartiUK  IMHO this can be included in default aliases.

**Comment by gustavohenke** [comment]
It would be amazing if `~` could be used as a variable as well

**Comment by vladimir-kotikov** [comment]
I think here is two options. First is `set ~=%USERPROFILE%` and something like cd %~%\Documents will work then, but you will have to wrap tilda into `%%` always. Not sure that this will be valuable.
Second recipe is to place `home.lua` file with following content
```
local function tilde_match (text, f, l)
    if text == '~' then
        clink.add_match(clink.get_env('userprofile'))
        clink.matches_are_files()
        return true
    end
end

clink.register_match_generator(tilde_match, 1)
```
to Cmder's `config` directory. This will add ~ -> HOME expansion after {TAB} key press

**Comment by narnaud** [comment]
A last option is to use AutoHotkey

#IfWinActive ahk_class VirtualConsoleClass
::~::D:/nicolas
#IfWinActive

This will replace ~ by whatever you want, as soon as you type anotther character ('/' or Enter):
cd ~
>> user type '/', it becomes
cd D:/nicolas/

Note that it's working all the time in ConEmu, meaning it would work even if you ssh into another machine (whic seems plain wrong - I usually stop AutoHotKey aat this point)

**Comment by vladimir-kotikov** [comment]
Unfortunately all of these workarounds is just a surrogates and can't provide Bash-like  `~` replacement.

**Comment by MartiUK** [comment]
This will never happen, I suggest using PowerShell in cmder if you desperately want ~ aliased.

**Comment by nonbeing** [comment]
@vladimir-kotikov Thank you for the `home.lua` recipe - it's exactly what I needed!

**Comment by azuria-sky** [comment]
Works beautifully, thanks so much!

**Comment by DRSDavidSoft** [comment]
Sorry to revive this old issue, but I've written a small batch script that exactly handles this, and I think it's a better solution rather than aliasing `~` itself.

If anyone comes along in the future, please have a look here:
https://github.com/cmderdev/cmder/issues/1051#issuecomment-702983948
