### ISSUE TITLE
How to disable the crosshair

### ISSUE THREAD

**Issue by buckleyGI** [bliker/cmder#369]
I have been looking on and off to diable the "crosshair" that I somehow enabled.

I reviewed all settings but can't find it. Thank

![image](https://cloud.githubusercontent.com/assets/2102864/5737571/86c882b0-9be2-11e4-9a02-f3c16bd683a1.png)

**Comment by MartiUK** [comment]
Keys & Macro > Highlight rows/columns

Try to look a bit harder next time :smile:
