### ISSUE TITLE
Is Cmder known to cause a false positive alert from some virus checking software?

### ISSUE THREAD

**Issue by tryjude** [bliker/cmder#371]
I love this tool and hope to use it for years to come. However, my free Avast! software (which is generally a good anti-virus package) is giving me multiple alerts that this is some sort of malware or virus. It reports it as a Wind32:Evo-gen [Susp] virus which apparently is a broadly used category. In any case, is this a known issue and the alert is simply a false positive? Or is there some malware lurking in here somewhere?

I'm doubtful this codebase is infected but just thought I'd ask the question. 

Btw, I'm using the "mini" version of the tool. Thanks again.

**Comment by MartiUK** [comment]
There has been a few times where people have reported this and each time I have advised them to report this false postive to their AV provider, personally I use the built in Windows Defender on my Win 8.1 machine and I have no issues with cmder.

If you want to confirm its just you, try uploading the file that it flagged to Virus Total.

**Comment by idrissAbbou** [comment]
I reported to Avast and I get this message
"
Hello,

Thank you for reporting this.

Our virus specialists have been working on this problem and the provided file has been whitelisted.

For future reference you might also find the following article to be useful: https://support.avast.com/en-us/article/228/

Best Regards,
Prokop
The Avast Support Team
"
