### ISSUE TITLE
Possible to change TSA icon?

### ISSUE THREAD

**Issue by CumpsD** [bliker/cmder#373]
Is it possible to change the TSA icon? Currently it shows the default ConEmu icon.

**Comment by MartiUK** [comment]
Maybe <sup>:tm:</sup>

I need to look into other issues but if you find out what it is be sure to send off a pull request.

**Comment by CumpsD** [comment]
TM ? what does it stand for? (trade mark?)

**Comment by CumpsD** [comment]
Actually, you support icons :)

https://github.com/bliker/cmder/blob/f4bca30e11f836481569dd1bfe103f244c63f153/launcher/src/CmderLauncher.cpp#L101-L105

But for some reason I had no ```icons``` directory in the cmder zip I downloaded fromt the main page.

Just confirmed, from the main page, this download does not contain the ```icons``` directory: https://github.com/bliker/cmder/releases/download/v1.1.4.1/cmder.7z

So it's an easy fix, without a PR ;)

**Comment by Stanzilla** [comment]
I wish @bliker would come back but looks like he has switched to OS X :(

**Comment by MartiUK** [comment]
I'll look into that for the next release, the packignore file doesn't specify that the icons folder is to be ignored.

**Comment by Danita** [comment]
Temporary solution: Download this repository ZIP file from the root (not the release download link) and extract the `icons` folder into your Cmder folder along with `bin`, `config` and the others.
