### ISSUE TITLE
UI broken characters

### ISSUE THREAD

**Issue by AndreyUtka** [bliker/cmder#375]
I use cmder on windows 10 preview, and I saw that characters in console is broken.
How it can be fixed?

![](http://content.screencast.com/users/Andrey.Ctkn/folders/Jing/media/d044833e-d1fd-4d98-86fb-5566c69f4211/2015-01-24_1219.png)

**Comment by bweston92** [comment]
I am too getting this issue.

**Comment by nicolapcweek94** [comment]
Can confirm, running on the latest Windows 10 x64 build
![8a62cd4c8668ec17827679db52258d5b6ee948b24d827adf2ed2f530dbaa469f](https://cloud.githubusercontent.com/assets/1051482/5909001/b13f994c-a5ac-11e4-9531-db0a66e3f9e8.png)

**Comment by MartiUK** [comment]
The latest clink version fixes this and I'm releasing a new version of cmder with clink very soon...
