### ISSUE TITLE
create alias with multi word parameter

### ISSUE THREAD

**Issue by luisrudge** [bliker/cmder#376]
I want something like that:

`gc=git commit -m $1`

But when i hit `gc "my message"`, the commited message is just `"my"`.

How can I add the entire string as one parameter?

**Comment by r3Fuze** [comment]
You can use `$*` to get all the arguments.
So `gc=git commit -m $*` would do what you need.

**Comment by luisrudge** [comment]
Thaaaaaanks very much! :)

Enviado pelo meu Windows Phone
________________________________

**Comment by sinrise** [comment]
This does not work. I get an error: 'fatal: Paths with -a does not make sense.' My alias is
gcam=git commit -am &*

**Comment by sinrise** [comment]
I tested it identical to the example above and it still does not work. I get 'error: pathspec '...' did not match and file(s) known to git.' for each word in my commit message, with '...' being each word in the commit message.

**Comment by abdallahelmalawy** [comment]
Good job man
