### ISSUE TITLE
Lag after losing focus

### ISSUE THREAD

**Issue by JPNaude** [bliker/cmder#385]
In many cases I find a long lag after I return to the Cmder window after it lost focus to do something else. Commands does not work and I have to wait about 10seconds before it starts to respond again.

Is this a known issue? Any workarounds?

**Comment by rmorrin** [comment]
There was a similar issue some time ago, but I was under the impression it had been fixed. Either way, the solution that worked for me can be found [here.](https://github.com/bliker/cmder/issues/40#issuecomment-29648808)

**Comment by JPNaude** [comment]
Ok thanks, I don't think I'm running the latest version.
Have set it and will check if it still happens.

**Comment by MartiUK** [comment]
This has been fixed in the latest version but if you want to fix it yourself, untick this option:
https://github.com/bliker/cmder/issues/109#issuecomment-31736141
