### ISSUE TITLE
Cmder unable to find .ssh folder

### ISSUE THREAD

**Issue by willemdh** [bliker/cmder#387]
Hello,

I installed Cmder with Chocolately on Windows 8.1. It seems by default it installs under C:\Tools

Then I installed boot2docker for Windows.

When I ssh to the boot2docket vm from boot2docker start, it does not ask for any password, as the public / private keys are in C:\Users\Willem\.ssh
I would have expected Cmder also look in C:\Users\Willem\.ssh for keys, but apparently it does not. When I explicitly define the location of the boot2docker private key like this it does work:
ssh -v2 -i C:\Users\Willem\.ssh\id_boot2docker docker@192.168.59.103

So is there a way to make Cmder look at C:\Users\Willem\.ssh for keys? Where does it look by default? I tried moving the .ssh folder to C:\, to C:\tools\cmder\config

Please advise how to make Cmder look at the correct .ssh folder.

Tried adding environment variable 'HOME' with value '%USERPROFILE%' but it didn't not help.

Thanks and grtz

Willem

**Comment by MartiUK** [comment]
I do not maintain the chocolatey version of cmder, my only suggestion is to try an official release here on GitHub and try using that.

**Comment by willemdh** [comment]
Thanks martiUK. I will try your suggestion. Can you just tell me where Cmder will look by default for ssh keys?

**Comment by MartiUK** [comment]
By default msysgit uses ```%HOME%\.ssh```
So In your case that would be ```C:\Users\Willem\.ssh```

**Comment by willemdh** [comment]
I downloaded the latest version of Cmder from Github and put it in my Dropbox account this time/

C:\Users\Willem\.ssh exists and has the correct keys in for the boot2docker vm as when I use the boot2docker start.sh script, I do not have to give any password.

When I use Cmder to ssh to boot2docker
ssh docker@192.168.59.103

It keeps asking me for my password hence I still think Cmder / msysgit does not find %HOME%\.ssh

Tried adding HOME environment variable to Windows, but it does not seem to help. 

![windows_env](https://cloud.githubusercontent.com/assets/6462991/6110312/30ebb764-b081-11e4-88c5-3b70fed44219.PNG)

**Comment by MartiUK** [comment]
Just to clarify, the folder you have your keys in is ```C:\Users\Willem.ssh``` not ```C:\Users\Willem\.ssh```?

**Comment by willemdh** [comment]
Hey MartiUk,

The folder where my ssh keys are located is C:\Users\Willem\.ssh

.ssh is a folder, see this screenshot:

![windows_ssh](https://cloud.githubusercontent.com/assets/6462991/6111883/79e58976-b08c-11e4-9632-998c9a51fcbf.PNG)

**Comment by bitHugger** [comment]
Have the same pathing and got the exact same problem

**Comment by Fumler** [comment]
Same problem here.

**Comment by MartiUK** [comment]
If you run `ssh -v git@github.com` where is it looking for the identity files? Mine for example says `debug1: identity file /c/Users/Martin/.ssh/id_rsa type 1`

**Comment by Fumler** [comment]
Aha, that fixed it for me, I was using the one github for windows created, which was named github_rsa, just renamed it id_rsa :+1: Thanks.

**Comment by willemdh** [comment]
λ ssh -v git@github.com
OpenSSH_4.6p1, OpenSSL 0.9.8e 23 Feb 2007
debug1: Connecting to github.com [192.30.252.129] port 22.
debug1: Connection established.
debug1: identity file /c/Users/Willem/.ssh/identity type -1
debug1: identity file /c/Users/Willem/.ssh/id_rsa type -1
debug1: identity file /c/Users/Willem/.ssh/id_dsa type -1
debug1: Remote protocol version 2.0, remote software version libssh-0.6.0
debug1: no match: libssh-0.6.0
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_4.6
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-cbc hmac-sha1 none
debug1: kex: client->server aes128-cbc hmac-sha1 none
debug1: sending SSH2_MSG_KEXDH_INIT
debug1: expecting SSH2_MSG_KEXDH_REPLY
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)?

**Comment by willemdh** [comment]
MartiUK, I got it working! It was some time ago I did this, so I though I'd generate new keys and try again. After doing the following when in the user folder:

ssh-keygen -t rsa

ssh-copy-id docker@192.168.59.103

cat ~/.ssh/id_rsa.pub | ssh docker@192.168.59.103 "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"

I can connect from Cmder to Boot3Docker without password. Thanks for the help and the patience!

**Comment by MartiUK** [comment]
@willemdh If you're trying to ssh to your boot2docker you need to specify the id file you want ssh to use i.e. `ssh -i c:\Users\Willem\.ssh\id_boot2docker username@hostname`

to make ssh use it all the time add this into your .ssh/config file
```
Host hostname
  IdentityFile C:\Users\Willem\.ssh\id_boot2docker
```

**Comment by MartiUK** [comment]
@willemdh Ah, that's another way of doing it.

**Comment by willemdh** [comment]
Thanks Marti! And good job on the Cmder. I'm using it alot. THe only other issue I still have is this https://github.com/bliker/cmder/issues/379 
Any ideas? :)

**Comment by Ciwan1859** [comment]
@MartiUK I'm having the same issue but with BitBucket. In Git Bash, I only have to input my password once, then I can `git pull` and `git push` as many times as I want without the need of a password. But on Cmder, each time I do a remote git command, it asks for the bitbucket password!

My `.ssh` folder sits here `C:\Users\jkhalaf\.ssh` and in the `config` file I have:

`Host bitbucket.org
 IdentityFile C:\Users\jkhalaf\.ssh\id_rsa`

Any ideas?

**Comment by MartiUK** [comment]
@Ciwan1859 Have you added the key to the ssh-agent?

**Comment by Ciwan1859** [comment]
@MartiUK, yep I have. I tried to do it again in Cmder, but I got the following:

![Cmder ssh-add](https://content.screencast.com/users/JKhalaf/folders/Snagit/media/41d68138-76d7-4d4a-8a08-220a9d32b4f3/08.17.2017-09.31.png)

But in Git Bash, it was added fine!

![GitBash ssh-add](https://content.screencast.com/users/JKhalaf/folders/Snagit/media/39cabfbb-8dc5-46dc-8963-6b8e0a7b19ae/08.17.2017-09.32.png)

Afterwards, I restarted Cmder, but again it asks for the password on each remote git command.

**Comment by rmsraph** [comment]
try this: C:\\Users\\Willem\\.ssh\\id_rsa
