### ISSUE TITLE
Can't run cmder.exe

### ISSUE THREAD

**Issue by Limro** [bliker/cmder#389]
http://www.reddit.com/r/programmingTools said this was the shit and I wouldn't be sad to walk away from PowerShell.
But when it doesn't run at all, I get a bit sad.

The process:
- Download .7z-file (24.7 MB) version
- Extract to C:\Programming Filez (x86)\CMDer\
- Move CMDer.exe, msvcp120.dll, msvcr120.dll and Version v1.1.4.1 to \bin\ folder
- Open PowerShell 
- cd to folder
- Run Cmder.exe /REGISTER ALL, which yells error
- Open PowerShell as admin
- Run the same command - no output
- Double click the Cmder.exe - nothing happens
- ./Cmder.exe - nothing happens
- Check Path variables - no changes (Cmder.exe not added)

Got a fix?

**Comment by Stanzilla** [comment]
Leave out that part 
```
Move CMDer.exe, msvcp120.dll, msvcr120.dll and Version v1.1.4.1 to \bin\ folder
```

**Comment by MartiUK** [comment]
Who told you to move the binary files into a bin folder?

**Comment by Limro** [comment]
> Who told you to move the binary files into a bin folder?

From the installation manual in the ```README.md```:
```
Step 3: Place files into bin folder, it will be injected into your PATH.
```

**Comment by MartiUK** [comment]
@Limro That's for other binaries or programs you want to use, why would we ask you to move the cmder launcher binaries yourself?

**Comment by Limro** [comment]
@MartiUK  It's odd, right. But the manual didn't say which files to move, and I wanted the cmder to be in my PATH :)

**Comment by MartiUK** [comment]
@Limro The normal usecase is for you to have it anywhere you like but launching it using the launcher executable (cmder.exe), from what it sounds like you are opening up a powershell instance and then using that to run cmder. cmder is your terminal emulator/console/'dos prompt' as it runs cmd, powershell or whatever for you.

**Comment by Limro** [comment]
Yup - I think I got it now :+1: Thanks a lot.

**Comment by MartiUK** [comment]
@Limro No problem :+1:
