### ISSUE TITLE
Can't edit /config/Aliases?

### ISSUE THREAD

**Issue by Limro** [bliker/cmder#391]
I get a "Access denied" when I try to edit this one.
But I have full control of it, according to permissions.

Cmder.exe is not open, so it's not,that the program is using the file...

Any suggestions?

**Comment by Limro** [comment]
Right, that turns out to be my own fault.
Is c:\Program Files\ a bad place to have my program? Is it better elsewhere?

**Comment by MartiUK** [comment]
Probably best to have it in a location where you have permissions. I have it on the desktop for example, but have a shortcut to the cmder.exe in the taskbar.
