### ISSUE TITLE
request: oh-my-git

### ISSUE THREAD

**Issue by tomByrer** [bliker/cmder#394]
Fancier git prompt, hides when not in git folder.
https://github.com/arialdomartini/oh-my-git

**Comment by MartiUK** [comment]
oh-my-git requires sh which cmder doesn't distribute (as arguably this is for windows users), you can open cygwin with cmder which you could use to get the prompt.

**Comment by tomByrer** [comment]
> you can open cygwin with cmder which you could use to get the prompt

Good suggestion.
Is there a way to get a similar prompt with what cmder has now?

**Comment by MartiUK** [comment]
You will have to find or rewrite oh-my-git to work with cmd or powershell.
