### ISSUE TITLE
time command

### ISSUE THREAD

**Issue by keradus** [bliker/cmder#395]
Hi, I just start using cmder. Great perception so far!
I have one problem - `time` command is windows command to set system time and not linux command to measure time of execution.
Could you help please?

**Comment by MartiUK** [comment]
time is usually builtin to bash or zsh, so msysgit doesn't include it.

**Comment by r3Fuze** [comment]
Using `time /T` will print the current time. Unfortunately there isn't any options for how to format it. More info here http://ss64.com/nt/time.html

**Comment by MartiUK** [comment]
You can try something like ```bash -c 'time cmd /C "echo hello"'``` although I can't figure out why cmd isn't terminating

**Comment by keradus** [comment]
I don't want the current time @r3Fuze , I want linux time command to measure time of execution.

@MartiUK this won't work when I just run 3rd party tool, which uses time command.

**Comment by r3Fuze** [comment]
Oops, my bad. Didn't read the question correctly.

**Comment by MartiUK** [comment]
@keradus I'd suggest running it with cygwin then, I've recently added a guide to the wiki here: https://github.com/bliker/cmder/wiki/Integrating-Cygwin

**Comment by keradus** [comment]
Thank you!
