### ISSUE TITLE
Wrong icon path for context menu entry

### ISSUE THREAD

**Issue by raphinesse** [bliker/cmder#403]
After executing `.\cmder.exe /REGISTER ALL`, the icon paths in the registry are set to `{cmder_home}\icons\cmder.ico` while it probably should be `{cmder_home}\Cmder.exe`, since the build does not include the icon directory (v1.1.4.1).

**Comment by MartiUK** [comment]
This will be fixed in the next version.

**Comment by raphinesse** [comment]
Nice to hear. Sorry for the dup, must have overlooked the issue.
