### ISSUE TITLE
Context Menu entry in File Explorer

### ISSUE THREAD

**Issue by 1ClickComputing** [bliker/cmder#404]
I would be great to have an entry in the File Explorer context menu so that you can do right click open cmder here. https://msdn.microsoft.com/en-us/library/windows/desktop/cc144171%28v=vs.85%29.aspx

**Comment by isdsc** [comment]
This feature is already available, you just need to enable it: [Shortcut to open Cmder in a chosen folder](https://github.com/bliker/cmder#shortcut-to-open-cmder-in-a-chosen-folder).

**Comment by 1ClickComputing** [comment]
Yes but it would be nice if it was a default feature.

**Comment by Jackbennett** [comment]
Cmder is supposed to be pretty non-invasive so just jacking everyones context menu is a bit impolite. Personally I like there being no difference by default of the portable or installed versions.

Maybe if the project had a few more settings to justify it there could be a list of settings functions for enable/disable features or just a .cmder config profile script.

Also, Cmder missing in explorer is issue 404 hehheh :)

**Comment by MartiUK** [comment]
@1ClickComputing Sorry but cmder is intended to be portable and standalone (or non-invasive as @Jackbennett said), so dropping registry entries by default into every PC is not an option.
