### ISSUE TITLE
How do you create an alias?

### ISSUE THREAD

**Issue by notflip** [bliker/cmder#421]
Hi

I want to create aliases to work a litle faster.
Tried creating a .bashrc folder in my home dir but it's not working

Thanks

**Comment by r3Fuze** [comment]
You can create your aliases in the `config/aliases` folder or with the `alias` command.
There was also a small part about aliases in the readme:

### Aliases
You can define simple aliases with command alias name=command.
For example there is one defined for you alias e.=explorer .
All aliases will be saved in /config/aliases file

**Comment by notflip** [comment]
Perfect! Thank you very much

**Comment by janacm** [comment]
Can someone tell me what I'm doing wrong here?

![image](https://user-images.githubusercontent.com/2055312/33488714-85116966-d67f-11e7-8b79-2e584f18f0ae.png)

**Comment by power-media** [comment]
To add some to answer above, current cmder (I don't know since when though) , once you have 'config/aliases' file created, on new console window launch automatically converts 'config/aliases' file to 'user-aliases.cmd', that works now in cmder.

**Comment by adam-arold** [comment]
If I use the `alias` command it works but only for the given session. If I restart cmder it is not working anymore.

**Comment by power-media** [comment]
@adam-arold, aliases need to be stored in config file to be persisted.

**Comment by adam-arold** [comment]
I have my aliases in the `config/aliases` file and they are not available form Cmder. This is how this file looks like:

```
gcb="./gradlew clean build --parallel"
gfb="./gradlew assemble --parallel"
```

What could be the problem?

**Comment by daxgames** [comment]
Do you have a %cmder_root%\config\user-aliases.and file? Never versions of cmder 1.3.2+, I think, store aliases in this file.

**Comment by daxgames** [comment]
The alias command run in 'cmder' shell based on cmd.exe should write the alias to the file I mentioned in my last post preserving it for future sessions.

If using a 'bash' shell aliases created using the alias command are not saved unless you manually add them to '%cmder_root%/config/user-aliases.sh'

**Comment by adam-arold** [comment]
I have the `user-aliases.sh` file and the aliases are in it but they don't work.

**Comment by daxgames** [comment]
@adam-arold. File content?

Should look something like:

```
alias aliasname='cmd args'
alias aliasname2='cmd2 args2'
```

**Comment by justinlazaro-ubidy** [comment]
```
ga=git add .
gc=git commit -am
gpm=git push origin
gpl=git pull origin
```

is this possible? 

`gpm myrepo`
`gc "something"`

**Comment by adam-arold** [comment]
For some reason the `alias` command did not add the `alias` prefix to the entries in the `user-aliases.sh` so I ended up adding them by hand. Now it works, thanks!

**Comment by daxgames** [comment]
@adam-arold All is working as expected.  The alias command in bash sets an alias for the running session only.  To make it permanent and cmder portable you add it manually to the file I told you about.  If you are not worked about it being portable the bash way would be to manually add it to the ~/.bashed file.

**Comment by xelra** [comment]
I have the `user-aliases.cmd` file and my aliases are in there. However, I cannot use any of the aliases in Cmder. Not even the default ones like `e.`.

**Comment by daxgames** [comment]
@xelra what version of cmder? If not latest, download the latest and follow the upgrade procedure in the readme.md.

**Comment by xelra** [comment]
@daxgames Thanks that fixed it. For some reason I was under the impression that Cmder was updating automatically.

**Comment by zidein07** [comment]
@justinlazaro-ubidy did you find solution ?

**Comment by jakoandersen** [comment]
How about passing the arguments on to the aliased command?
```bash
alias gd=git diff
```

Use it like:
```bash
gd --staged
```

**Comment by daxgames** [comment]
@maxpower9000 the "don't" is syntax for linux/Unix

The "do" is syntax for 'cmder' command alias.bat

**Comment by daxgames** [comment]
@jakoandersen is that a question?  If so, Cmder aliases in cmd based shells are based on doskey.  See the doskey macro [docs]( https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey) details on how to do advanced aliases.

**Comment by johnyluyte** [comment]
I'm using Cmder Version 180528

In `\cmder\vendor\`, there is a file called `user-aliases.cmd.example`, it contains the following:

````
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
gg=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
````
I duplicated this file and rename the duplicated file to `user-aliases.cmd`.

That is, I now have a `\cmder\vendor\user-aliases.cmd`

I add `ll=ls -al` to the last line of the file. Save it.

But in Cmder, I still cannot use the command `ll`. What am I doing wrong?

**Comment by johnyluyte** [comment]
@daxgames Thanks for the tips. 

Instead of  `\cmder\vendor\user-aliases.cmd`, which does not work.

Now I have `\cmder\config\user-aliases.cmd`, which is working, thanks you.

**Comment by Stanzilla** [comment]
Looks like a bug to me https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L253

**Comment by theyak** [comment]
I have %cmder_root%\config\user-aliases.cmd. It came pre-installed with Laragaon but none of the aliases in it work. vendor\init.bat does seem to be trying to load it. 

When I do alias vi=vim on the command line, vi continues to not work.

**Comment by panchalkalpesh** [comment]
The solution that seemed to have worked (**cmder ^v1.3.6**)

Open up the following in your text editor:
_CMDER_ROOT_/**config/user-aliases.cmd**


Extend the file by appending aliases you need: 
```cmd
;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"

ll=ls -la
```



Hope this helps you guys!

[Kalpesh Panchal](http://kalpeshpanchal.in/)

**Comment by rakismelange** [comment]
https://github.com/cmderdev/cmder/issues/421#issuecomment-364017376
@justinlazaro-ubidy 

Totally possible just use '$*'
e.g.
gpm=git push origin $*
gc=git commit -am $*

**Comment by ppumkin** [comment]
not sure if I am being thick (most likely cause its late) but im trying to added `alias k=kubectl`
It is in the config file but i get error. Also the e. does not work either?

🆘  Help 🆘 

![image](https://user-images.githubusercontent.com/1249683/48922436-92352500-ee9e-11e8-963a-d2cdf455f72b.png)

**Comment by Zontir** [comment]
> How about passing the arguments on to the aliased command?
> 
> ```shell
> alias gd=git diff
> ```
> 
> Use it like:
> 
> ```shell
> gd --staged
> ```

This didn't work out for me.
I'd like to create an alias where I could pass the parameter manually.
alias r=php artisan migration:refresh
So when I run r --seed the console just count the r without the parameter --seed
Can someone help me with this?

**Comment by dharif23** [comment]
I think there is a misunderstanding with what to put it in the aliases file.
if you put `alias ll=ls -la` it doesn't seem to work because of the preceding `alias` flag. It's already in the aliases file. Just put any command you want to create an alias to with a preferred name into `cmder/config/user-aliases.cmd` like this `ll=ls -al` save the file restart `cmder`.

**Comment by daxgames** [comment]
Cmder cmd session aliases are based on [doskey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey).  Look there for syntax.

Also no need to restart cmder, just execute `user_aliases.cmd` if you edit it directly.

**Comment by veex-ua** [comment]
In case anyone still strugling with creating aliases for ```bash``` shell, adding them to ```%cmder_root%/config/user_profile.sh``` with this syntax ```alias la='ls -la'``` worked for me.

**Comment by bholmquist11** [comment]
Hi @daxgames and everyone! 

Having issues - I'm using Bash / Ubuntu distribution {WSL::bash}. Running cmder out of my downloads folder at the moment '/mnt/c/users/Laptop/Downloads/cmder'. I run that executable. Certain default aliases work - for example, clear=cls does clear my screen. however, changes to user-aliases.sh or user-aliases.cmd don't have any effect. If I switch clear to clear1, clear is still the working command.

It seems to be referencing a different user-aliases file tahtn what i'm changing. Thoughts?

I'm modding:
`%CMDER_ROOT%/config/user-aliases.sh`
`%CMDER_ROOT%/config/user-aliases.cmd`

Thanks in advance.

**Comment by 3nigm4** [comment]
hey guys I just installed cmder on windows 7 and i am trying to make this command work, could you help me out!?

```dhall-to-json` --pretty <<< '[ ./example.dhall, ./example.dhall ]'```

it says that << can not be used here. I am in a cmd.exe tab

**Comment by mshaaban0** [comment]
Found it in the _"Creating a macro"_ section in [doskey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/doskey) 

$1 through $9 | Represent any command-line information you want to specify when you run the macro. The special characters $1 through $9are batch parameters that enable you to use different data on the command line each time you run the macro. The $1character in a doskey command is similar to the %1 character in a batch program.
-- | --
$* | Represents all the command-line information that you want to specify when you type the macro name. The special character $\* is a replaceable parameter that is similar to the batch parameters $1 through $9, with one important difference: everything you type on the command line after the macro name is substituted for the $\* in the macro.



@jakoandersen @Zontir this worked from me

```bash
alias g=git $*
# or 
alias gd=git diff $*
```

**Comment by ryan-mccartney** [comment]
> In case anyone still strugling with creating aliases for `bash` shell, adding them to `%cmder_root%/config/user_profile.sh` with this syntax `alias la='ls -la'` worked for me.

After quite a bit of searching this is the one that did it for me. Thank you! Duplicating the user-aliases file as `user-aliases.sh` did nothing.

Note for others - you still need to restart the active console to have your changes apply.

**Comment by andrehgdias** [comment]
Didn't see anyone commenting about this option so here it is... If you're using bash, from git for windows for exemple, you can add your alias to the alias.sh file in "cmder\vendor\git-for-windows\etc\profile.d" with this sintax:
E.g: alias dev='cd E:/Files/Projetos && code'

**Comment by abhijit-hota** [comment]
Is there any way to pass default arguments? 

I have the alias `ngk=ngrok http $*` and I have to pass the arguments (here, the port) as `ngk 3000`. Can I set some defaults such that when I just call `ngk` then it starts as `ngk 3000`?

**Comment by daxgames** [comment]
@abhijit-hota you sould set an environment variable in `%CMDER_ROOT%\config\user_profile.cmd` and add that to the alias or you could create a separate alias.

**Comment by chrisant996** [comment]
> Is there any way to pass default arguments? 
> 
> I have the alias `ngk=ngrok http $*` and I have to pass the arguments (here, the port) as `ngk 3000`. Can I set some defaults such that when I just call `ngk` then it starts as `ngk 3000`? 
> 
> P.S. I could make a separate alias but just wanted to know.

These are `doskey` aliases. See `doskey /?` for help, and also a lot of information and samples are available via internet searches.

Doskey aliases don't have default values for arguments.  A .cmd script could be written to check for a missing argument and provide a default value.  A doskey alias can't do that on its own, though.

**Comment by abhijit-hota** [comment]
@chrisant996 Thanks for clarifying!

**Comment by daxgames** [comment]
How about:

```
alias ll=ls -la
ll
```

If you are in a cmder shell we write this to the `%cmder_root%/config/user_aliases.cmd` so it does survive across sesions.

**Comment by sfinktah** [comment]
@DRSDavidSoft I'm sure they're all wonderful tools.  My brief thought was simply that it would be easier to have something in-place that responded to `sudo` (even if it just spouted information on how to get a real `sudo`).  It just sounds easier that trying to correct OpenAI's 4o model. 

disclaimer: I confess I did start renaming `apt-cyg` to `apt-get` many years ago, so I might just be lazy.
