### ISSUE TITLE
How to redirect Window's cmd.exe to Cmder's cmder.exe?

### ISSUE THREAD

**Issue by SupaHam** [bliker/cmder#426]
How would one go about redirecting Window's cmd.exe to use Cmder's cmder.exe (the emulator i think you call it)? This is what I get when I launch cmd.exe without cmder.exe being already active http://supa.me/0XoovU.png. However, if Cmder was already active, cmd.exe uses the prettified emulator.

**Comment by MartiUK** [comment]
cmder.exe is just a launcher, it's not a replacement for cmd.exe

What I think you're looking for is in Settings > Integration > Default term

**Comment by SupaHam** [comment]
Sorry for my lack of knowledge of more appropriate terms. If I were to execute a batch file (or run cmd.exe) whilst cmder is NOT active, the UI would look like so: http://supa.me/0XoovU.png. But if I attempt to execute a batch file (or run cmd.exe) whilst cmder is active THEN, the UI looks like so: http://supa.me/iHdU5G.png.

The default term option only guarantees that cmder be used when cmd.exe is to launch, but it does not use the same UI.

**Comment by MartiUK** [comment]
Yeah, that's right.

There's no way at present to tell conemu to use a certain task when running cmd, all it does is take what you were about to run.

For example, if all you did was run cmd in the run dialog. ConEmu runs this:
```ConEmu.exe /single /cmd -new_console:n "C:\Windows\system32\cmd.exe" ```
From what I can ascertain, there isn't much we can do from here without changing conemu unfortunately.

Perhaps try to have ```call %CMDERDIR%/vendor/init.bat``` at the start of your batch files or something similar.

**Comment by MartiUK** [comment]
You can see an explanation here: https://code.google.com/p/conemu-maximus5/wiki/DefaultTerminal

**Comment by SupaHam** [comment]
Ah, no worries then. I can live with the generic look. Thanks for your help.
