### ISSUE TITLE
How to update Git?

### ISSUE THREAD

**Issue by zzaebok** [bliker/cmder#428]
I had installed Git 1.9.4. Recently I've decided to update Git to 1.9.5. Update was successful, but now cmder says that git version still 1.9.4. E.g. when I type `git --version` in cmd it says `git version 1.9.5.msysgit.0`, but cmder says me `git version 1.9.4.msysgit.0`
![git-version](https://cloud.githubusercontent.com/assets/2868392/6705554/13b1ad86-cd67-11e4-8096-9fb4f3780446.png)
How to fix that?

**Comment by cgonzalezdai** [comment]
check out this https://github.com/bliker/cmder/issues/183

**Comment by kalvn** [comment]
If you want to keep it in cmder folder:

1. Rename `C:\path\to\cmder\vendor\git-for-windows` into `C:\path\to\cmder\vendor\git-for-windows.old`
2. Download the last portable version of Git for Windows with the last link on [this page](https://git-scm.com/download/win) **Git for Windows Portable ("thumbdrive edition")**
3. Extract it in `C:\path\to\cmder\vendor\git-for-windows`
