### ISSUE TITLE
Shortcut missing icon in context menu

### ISSUE THREAD

**Issue by Macsch15** [bliker/cmder#433]
I did everything as it is in the docs (.\cmder.exe /REGISTER ALL).

![2015-03-19 13-29-46](https://cloud.githubusercontent.com/assets/1592053/6730352/0eeead82-ce3c-11e4-98e6-6d5e9928d6c0.png)

Windows 7 x64

**Comment by MartiUK** [comment]
The icons were not included in the last release, extract the icons folder from this zip https://github.com/bliker/cmder/archive/master.zip into your cmder folder. This is already fixed for 1.2.
