### ISSUE TITLE
Feature request: per-project presets

### ISSUE THREAD

**Issue by CezaryDanielNowak** [bliker/cmder#435]
Usually our flow when working on project looks like:
- open terminal, run command 1,
- open new terminal tab, run command 2,
- open new terminal tab, cd to the project, run command 3
- open new terminal tab and `git status`
I also like to rename each tab, to fit my needs

real life example:
`brunch.io` for compiling sources, `express` for file serving, `mongod` for database, and `deployd` for backend

It would be cool, if I could save the preset, that each time I get same tabs.

**Comment by MartiUK** [comment]
There is an options in Settings > Startup to autosave/restore opened tabs.

**Comment by MartiUK** [comment]
If that isn't what you want, you can create your own task in setting and give it all the tabs you want and then start that task and in Startup options set that task as the startup.
