### ISSUE TITLE
Is it possible to have preset tabs?

### ISSUE THREAD

**Issue by JosephSilber** [bliker/cmder#439]
Is it possible to have some pre-registered tabs opened on startup?

I work on many projects simultaneously and keep one tab open for each project. But whenever I restart my computer, I have to re-open all those tabs :disappointed: 

This is the feature I miss most from iTerm2 whenever I work on my Windows machine.

**Comment by vladimir-kotikov** [comment]
@JosephSilber, take a look at https://github.com/bliker/cmder/issues/435
