### ISSUE TITLE
How To?  Mandate a perl install other than MinGW's?

### ISSUE THREAD

**Issue by Muzical84** [bliker/cmder#444]
I suppose this is more of a general thing, but perl's my specific bone of contention at the present moment.  I have my own install of MinGW, for what it does, (and for installing faster than cygwin =-\ ) but for perl, I use Strawberry Perl.

I've tried modifying my init.bat:
```bat
@set git_install_root=%ProgramFiles(x86)%\Git
@set PATH=%CMDER_ROOT%\bin;%git_install_root%\bin;%SystemDrive%\Vim\vim74;%SystemDrive%\Strawberry\perl\bin;%SystemDrive%\MinGW\bin;%SystemDrive%\MinGW\msys\1.0\bin;%git_install_root%\cmd;%CMDER_ROOT%;%PATH%
```
and %SystemDrive%\Strawberry\perl\bin is also on my Windows 7 path, but when I took %SystemDrive%\MinGW\msys\1.0\bin OUT of my Windows path, to try and force use of my preferred Perl, it can't find that at all...  It IS finding other things I have in my path, though: git-bash, node, SilkSvn, etc.

I'm using the "mini" version, installed in my Dropbox.

**Comment by MartiUK** [comment]
I don't know for certain what Git you have install but try moving `%SystemDrive%\Strawberry\perl\bin` further left before `%git_install_root%` as I have perl.exe in my globally installed git.

**Comment by Muzical84** [comment]
Standard git bash (git-scm.com)

**Comment by MartiUK** [comment]
@Muzical84 No problem, I usually forget (I had to look it up again now) but Windows reads %PATH% left to right and uses whatever it finds first.
