### ISSUE TITLE
Lag returning to prompt (especially) in git repo

### ISSUE THREAD

**Issue by Keilan** [bliker/cmder#447]
When using cmder with git (where it shows the name of my currently checked out branch next to the location), I'm finding that my commands are executed quickly but there is a major delay returning to the prompt so I can enter in another command. I notice this to some extent when I'm not in a git repo, but then the delay is almost not noticeable (100-200ms I'd guess), as opposed to 1-2 seconds in a repo.

To give further details, in my repo if I type `ls`, the file list comes up immediately, then the current tab changes from saying "cmd.exe" to "git.exe", and only after 1-2 seconds do I get a lambda prompt again where I can enter further commands.

I'm running Windows 8.1 and cmder.exe is installed in Program Files. Let me know if any more details would be helpful.

**Comment by Jackbennett** [comment]
This is some problem with git, with that in mind could you just try to use some git command from a shell that isn't cmder/conemu. Just maybe commands like `git status` and checkout a couple of branches and status there. 

If git runs that fast it must be something in cmders prompt function trying to write the status line before returning. I've found having the git status line in the prompt does have a performance hit in the tenth of a second order you describe. Any prompt function that is not just a cmder thing.

**Comment by Keilan** [comment]
Hey Jack, thanks for the response. I opened Cmder and a standard windows Command Prompt and navigated to the same directory, results as follows:

Windows Cmd: ~1 second delay before git status output appears, prompt reappears immediately
Cmder: ~1 second delay before git status output appears, plus a roughly 1 second delay before prompt reappears

This is consistent with the `ls` output, where windows cmd is instant, and with Cmder the output is instant but there is a ~1 second delay before the prompt reappears. It seems like Cmder is running the given command as expected, but then doing something else that is causing a delay. Is there some sort of update function called when in a git repo? That would make sense given that even a non-git command such as `ls` results in a delay coming from git.exe.

**Comment by Jackbennett** [comment]
When the git prompt adds to the end of that line the branch / numbers e.g `[master 0 +1 0]` it's just formatting its own call to `git status`.

From what you describe I think you've got a slow git repository. You'd best find out how you could speed it up. I could just be sheer size. I'm sure there's some tweaks to make windows faster with git. 

To immediately speed that up you could remove the git parts of the prompt function cmder is calling.

**Comment by Jackbennett** [comment]
Learning some new stuff myself here, This first answer seems like some solid advice. Check the git manual first though to see what these commands really do to your repo. 

http://stackoverflow.com/questions/4485059/git-bash-is-extremely-slow-in-windows-7-x64

**Comment by Keilan** [comment]
Thanks Jack, that is indeed the issue - applying the 3 settings mentioned in that SO question improved it quite a bit (I'd estimate the delay is down to 300-400ms from 1-1.5 seconds). I might look into removing the "git status" part of the prompt, as it is much more usable now, 300-400ms is still a bit much. Do you know if a setting exists for that? Or will I have to edit the source?

Anyways, marking this as closed, as the call to git status explains the issue. Thanks!

**Comment by vladimir-kotikov** [comment]
@Keilan you can try to replace `if...end` block here: https://github.com/bliker/cmder/blob/master/config/git.lua#L35 set  with the foolowing line `color = colors.clean`. This will decrease delays twice, but you will lose colored branch name depending on repo status.

**Comment by Jackbennett** [comment]
I will try to add some kind of setting to flip this in the powershell side of the console for a future release. Probably not the next release though. At least git is faster now.

**Comment by ritave** [comment]
I'd like to have an option to disable git showing anything on the prompt. It still slow on some occasions.

**Comment by xseneque** [comment]
I'd also like a way to disable git looking at my current repo as it gives me 30+ sec delay. It's a massive repo. I really don't care about it telling me i'm in the master branch.

How can I disable any git stuff. I just want a command prompt.

**Comment by schmich** [comment]
I'm in the same boat as @xseneque. I have a large repo where `git status` takes around a second, so running any commands under the repo just kills all flow.

I'd really like to disable git integration. Is there any simple workaround for now, or do we have to wait for a release?

**Comment by justaniles** [comment]
After some searching, I've been able to remove git integration in the prompt, resulting in no lag when inputting commands in a git repo! The following modifications must be done to your ```cmder/vender/clink.lua``` file:

On [line 41](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L41), remove ```{git}{hg}``` to prevent git/mercurial branch from being printed in your prompt:
```lua
local cmder_prompt = "\x1b[1;32;40m{cwd}\n\x1b[1;30;40m{lamb} \x1b[0m"
```

Comment out [lines 266-267](https://github.com/cmderdev/cmder/blob/master/vendor/clink.lua#L266-L267) to prevent git and mercurial plugins from running every time you press enter:
```lua
--clink.prompt.register_filter(hg_prompt_filter, 50)
--clink.prompt.register_filter(git_prompt_filter, 50)
```

As a note, you may want to back up this ```clink.lua``` file somewhere, in case it gets overridden after a cmder update.

Hope this helps!

**Comment by schmich** [comment]
@justaniles Awesome, that's exactly what I was looking for, thanks for the help!

**Comment by janschulz** [comment]
So what should the actual solution be here? If it should be per repo, we need to write something to the `.git\` folder?

So something like this:

```
if not clink.get_env('CMDER_DISABLE_SCM_PROMPT') then
   -- find git dir ...
   if not git_dir_contains('cmder_disable_git_prompt') then
       -- replace {git} with the right things -> old stuff
       return
   end
end
-- replace {git} with ""
```

**Comment by xseneque** [comment]
Thanks @justaniles ; works like a charm!!

**Comment by valix85** [comment]
Hi guys, I have same problem... every git command spend a lot of seconds to end and return to input. I come back to windows cmd for now... I'm waiting for update.

**Comment by DaveInCaz** [comment]
Is the post by justaniles on Sep 1, 2016 still the most up to date advice for this? Is there a configuration option to remove the SCM details from the prompt?

**Comment by mloskot** [comment]
In the traditional cmd with clink, there are two `git` look-ups run in `clink.lua` to refresh the prompt:

- `get_git_branch`  - fast, reads `.git/HEAD`
- `get_git_status` - slow, `git status` which is used to decide about dirty/clean colourisation. In the whole git repo of Boost, this one takes annoyingly long time.

So, instead of disabling git information in the prompt completely, some may prefer to just get rid of the detailed/coloured status, keeping the current branch info:

```
λ diff -Nua c:\apps\cmder_mini\vendor\clink.lua.original c:\apps\cmder_mini\vendor\clink.lua
--- c:\apps\cmder_mini\vendor\clink.lua.original        2018-04-09 09:54:20.468732700 +0200
+++ c:\apps\cmder_mini\vendor\clink.lua 2018-04-10 08:39:57.809013700 +0200
@@ -263,11 +263,12 @@
         local color
         if branch then
             -- Has branch => therefore it is a git folder, now figure out status
-            if get_git_status() then
-                color = colors.clean
-            else
-                color = colors.dirty
-            end
+            -- XXX: Disable git status due to lag in large repo
+            -- if get_git_status() then
+                 color = colors.clean
+            -- else
+            --     color = colors.dirty
+            -- end

             clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..branch..")")
             return false
```

Kudos to https://github.com/cmderdev/cmder/issues/447#issuecomment-244149494 for inspiration.

**Comment by mloskot** [comment]
@DGalt Try this

- edit `vendor\profile.ps1`
- find this bit
```
[ScriptBlock]$CmderPrompt = {
    $Host.UI.RawUI.ForegroundColor = "White"
    Microsoft.PowerShell.Utility\Write-Host $pwd.ProviderPath -NoNewLine -ForegroundColor Green
    checkGit($pwd.ProviderPath)
}
```
- remove `checkGit($pwd.ProviderPath)`
- save and relaunch cmder

**Comment by DGalt** [comment]
@mloskot perfect, thank you!

**Comment by SidShetye** [comment]
Can the dev re-open this issue? It's still a problem and all 'fixes' here are overwritten on an update. This belongs somewhere in settings than hardcoded in a `profile.ps1` script.

**Comment by loshjawrence** [comment]
Just discovered cmder today and downloaded to try it out. Ran into this issue in a large git repo (not all repo's do this). Every command is slow returning to the lambda prompt in the repo not just git commands. Tried all these fixes to no avail. Other terminal types (::bash ::mintty ::Powershell) don't have this issue. Otherwise very cool terminal.

**Comment by mahsanshaikh** [comment]
@mloskot  Solution works for me. Great thanks man.

**Comment by vineetmimrot** [comment]
One basic question, after making changes into clink.lua file, how to build it.

**Comment by victorigualada** [comment]
> In the traditional cmd with clink, there are two `git` look-ups run in `clink.lua` to refresh the prompt:
> 
> * `get_git_branch`  - fast, reads `.git/HEAD`
> * `get_git_status` - slow, `git status` which is used to decide about dirty/clean colourisation. In the whole git repo of Boost, this one takes annoyingly long time.
> 
> So, instead of disabling git information in the prompt completely, some may prefer to just get rid of the detailed/coloured status, keeping the current branch info:
> 
> ```
> λ diff -Nua c:\apps\cmder_mini\vendor\clink.lua.original c:\apps\cmder_mini\vendor\clink.lua
> --- c:\apps\cmder_mini\vendor\clink.lua.original        2018-04-09 09:54:20.468732700 +0200
> +++ c:\apps\cmder_mini\vendor\clink.lua 2018-04-10 08:39:57.809013700 +0200
> @@ -263,11 +263,12 @@
>          local color
>          if branch then
>              -- Has branch => therefore it is a git folder, now figure out status
> -            if get_git_status() then
> -                color = colors.clean
> -            else
> -                color = colors.dirty
> -            end
> +            -- XXX: Disable git status due to lag in large repo
> +            -- if get_git_status() then
> +                 color = colors.clean
> +            -- else
> +            --     color = colors.dirty
> +            -- end
> 
>              clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..branch..")")
>              return false
> ```
> Kudos to [#447 (comment)](https://github.com/cmderdev/cmder/issues/447#issuecomment-244149494) for inspiration.

For me, commenting the `if-else` block caused an error due to color property can't be found. I just removed the `color..` property on the `string.gsub` call like this:

```
clink.prompt.value = string.gsub(clink.prompt.value, "{git}", "("..branch..")")
```

**Comment by mloskot** [comment]
Yes, that snippet above needs refinement. Here is the current version I use:

https://github.com/mloskot/wsl-config/blob/36793de0ba02de68268da554f0d548228fa57b84/win/cmder_mini/vendor/clink.lua#L365-L370

The whole idea is to avoid the heavy call to `get_svn_status()`

**Comment by mloskot** [comment]
The earlier tweak does not work for Cmder 1.3.11, but it should be easy to adjust the new versions of the `get_git_status` and `get_git_conflict`.

For large repos with lots of submodules, like https://github.com/boostorg/boost/, these two tweaks are sufficient for me to greatly speed the git prompt:

Simply, add `--ignore-submodules` to these two `git` commands:

https://github.com/cmderdev/cmder/blob/89499f2a6068980256ca1132714407fdbcdc282a/vendor/clink.lua#L221-L222

https://github.com/cmderdev/cmder/blob/89499f2a6068980256ca1132714407fdbcdc282a/vendor/clink.lua#L236-L237

**Comment by lucas993** [comment]
> The earlier tweak does not work for Cmder 1.3.11, but it should be easy to adjust the new versions of the `get_git_status` and `get_git_conflict`.
> 
> For large repos with lots of submodules, like https://github.com/boostorg/boost/, these two tweaks are sufficient for me to greatly speed the git prompt:
> 
> Simply, add `--ignore-submodules` to these two `git` commands:
> 
> https://github.com/cmderdev/cmder/blob/89499f2a6068980256ca1132714407fdbcdc282a/vendor/clink.lua#L221-L222
> 
> https://github.com/cmderdev/cmder/blob/89499f2a6068980256ca1132714407fdbcdc282a/vendor/clink.lua#L236-L237

Sorry guys, `--ignore-submoduels` didn't help for me at all.  

For sure `git --no-optional-locks status --porcelain 2>nul` and `git diff --name-only --diff-filter=U 2>nul` are very slow on my system.  So I think this is the correct place to find a speed up.

**Comment by TimRudy** [comment]
Just to summarize the quick solution in 2019, this definitely solved my complaint with Cmder, that it took over 8 seconds every time I issued a command!

- Incidentally I had Settings -> Update -> "Preferred release type" set to "Stable" which was ConEmu 180626 that came from years ago - the developer might want to note this; I changed to "Latest", so I don't short-change myself for the coming few years, but this did not make any performance difference
- Go to C:\Program Files\Cmder\vendor, make a backup copy of clink.lua and edit it
- Delete the lines
  get_git_status()
  get_git_conflict()

- Just leave these lines in place:
        if branch then
            color = colors.clean
            clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..verbatim(branch)..")")
            return false
        end

Now commands are responsive! Instantaneous! Thank you to:
@mloskot
@justaniles Sep 1, 2016 https://github.com/cmderdev/cmder/issues/447#issuecomment-244149494

**Comment by rohitkrishna094** [comment]
@TimRudy I can guarantee that the solution that you provided works. I tried Mr.[mloskot's](https://github.com/cmderdev/cmder/issues/447#issuecomment-379992066) solution, but it didn't work for me.

I think commenting `get_git_status()` and `get_git_conflict()` is the key. Thanks.

**Comment by mloskot** [comment]
Re: https://github.com/cmderdev/cmder/issues/447#issuecomment-536690719

This is certainly not a competition but that comment may leave one quite confused.

AFAICT, the patched I presented in https://github.com/cmderdev/cmder/issues/447#issuecomment-379992066 produces this code

```
         if branch then
             -- Has branch => therefore it is a git folder, now figure out status
             -- XXX: Disable git status due to lag in large repo
             -- if get_git_status() then
                 color = colors.clean
             -- else
             --     color = colors.dirty
             -- end

             clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..branch..")")
             return false
```

which, clearly, is the equivalent code to the code @TimRudy presented in https://github.com/cmderdev/cmder/issues/447#issuecomment-532752032

```
        if branch then
            color = colors.clean
            clink.prompt.value = string.gsub(clink.prompt.value, "{git}", color.."("..verbatim(branch)..")")
            return false
```

@rohitkrishna094 I'd suggest you analyse the snippets more carefully, then you should avoid any disappointments.

**Comment by rohitkrishna094** [comment]
My bad, the diff had me confused. Would've been better if you included the output without diff in the first place. Either way thanks. And apologies. Have a nice day.

**Comment by SidShetye** [comment]
@daxgames and @Stanzilla : Can you re-open this issue to fix the lag issue bug in cmder? Guessing most folks have switched to the new Windows Terminal app but folks still seem to be tripping over this 4 year old issue. Seems silly to block the prompt(=UI) over a long running task. Quickest solution would be to make git status opt-in by default instead of opt-out by kludgy .lua hacks. Even better, put long running tasks on a background thread. 

Blocking the UI is ... so 90s.

**Comment by daxgames** [comment]
@SidShetye is this related https://github.com/cmderdev/cmder/issues/2178.

I have never actually seen this issue.

**Comment by mloskot** [comment]
@daxgames I doubt its related. This issue is specifically about `git` command, not any other commands. And, this issue has been extensively investigated.

You need sufficiently large repo to suffer from it.

**Comment by develorem** [comment]
I can confirm that this will happen whenever GIT is slow, for whatever reason, not just big repositories. In my scenario, its a brand new repo with only 2 branches and 3 commits. 
I have verified git itself is the issue on this Windows 10 PC. The fix defined by @TimRudy worked for me also. 

Have you considered: https://github.com/romkatv/gitstatus ?
Its benchmarks for hot runs are a compelling argument.
(Note I have not used 'gitstatus' myself)

Also for anyone else new to LUA, when I made a copy of my clink.lua file, at first I didn't change the file extension, and it seems it still got picked up and executed, meaning nothing got better at first!
You need to change the extension; I just renamed my old one 'clink.lua.old' - it worked after that.

**Comment by hackhowtofaq** [comment]
@mloskot please read carefully my issue, git + **all other Linux cmds** since cmder is using these cmds if git pre-exists.

**Comment by mloskot** [comment]
@hackhowtofaq I did read it and I keep my point that #2178 has nothing to do with the slowness of `git status` (command prompt lag) that we are discussing in this particular issue here.

I have two different sets of Unix commands in my environment: Git's and GnuWin32.
The GnuWin32 tools, not Git's, are available in my environment when e.g. PowerShell is loaded by Cmder. 

The `git status` is _equally_ slow for large repos with numerous submodules (e.g. Boost C++ libraries) regardless of shell (and Unix tools) loaded by Cmder, i.e. it is slow from Git Bash, CMD or PowerShell. Disabling `git status` in `clink.lua` is the workaround to avoid lags during prompt updates.

**Comment by daxgames** [comment]
@mloskot just clarifying.  Disabling git status in clink somehow fixes external git in Powershell loaded in Cmder?  Or any git, internal or external, in any shell loaded in cmder?

**Comment by mloskot** [comment]
@daxgames  Disabling `git status` in `clink.lua` is workaround for wherever `clink.lua` is used. In this context here it is for Cmder.

My apologies, I wasn't clear. In my earlier comment, I just wanted to explain that I don't see any connection
between the general slowness  of `git status` that also affects Clink/Cmder
and the slowness of Unix tools reported elsewhere.

To summarise, the problem we are discussing here is related to `git` command and is very simple:

- Current implementation of `git status` is intrinsically slow for large and submodule-arised repos
- Cmder's `clink.lua` relies on `git status`, hence the prompt update lags
- Workaround: disable `git status` calls from `clink.lua` to avoid the lags

**Comment by daxgames** [comment]
@mloskot Thanks, thats what I thought..  Just wanted it to be clear.
