### ISSUE TITLE
Error on cmder launch: "The syntax of the command is incorrect"

### ISSUE THREAD

**Issue by Muzical84** [bliker/cmder#454]
I use cmder at work and my workstation got restarted over the weekend, (with Win7 asking if I want to "start normally" and all that, so maybe restarted isn't quite the word.  I tried restarting Cmder and I'm getting an error:

"The syntax of the command is incorrect.

Current directory:
C;\Users\[me]\Dropbox\cmder_mini\bin

Command to be executed:
"C:\Windows\system32\cmd.exe" /C <Startup>

ConEmuC: Root process was alive less than 10 sec, ExitCode=1
Press Enter or Esc to close console..."

What causes this and how do I fix it?  I checked my alias and config files and they don't appear corrupted or incorrect.  (And anyway, I haven't touched either since Friday afternoon when this all worked.)

Thanks!

**Comment by Muzical84** [comment]
OK...perhaps never mind, because I found the icon hidden in my system tray, closed that, THEN tried starting Cmder by right-clicking a git repo and using the context menu...it spewed my ENTIRE local MySQL.ini into the window, but seems to be working...  (Took MySQL's command-line tools out of cmder's path and that seemed to stop the spewing, but then it complains that MySQL isn't a valid command???)

**Comment by MartiUK** [comment]
I'd hazard a guess that mysql is trying to spawn another cmd.exe window before running but I. I don't use mysql (at least on windows) is there a binary you can run that just runs the mysql command line tool by itself?

**Comment by Muzical84** [comment]
That's to what I was attempting to path: %ProgramFiles%\MySQL\MySQL Server 5.6\bin;

**Comment by m0ien** [comment]
i try to install babun 1.2 ; i have an error "The syntax of the command is incorrect" yon.ir/oVSwO  : (
what should i do?
