### ISSUE TITLE
Feature  Request : Save opened tabs and locations of the tabs

### ISSUE THREAD

**Issue by devsmart** [bliker/cmder#455]
I'd like to have feature to save last opened tabs and reopen those with last saved paths.

**Comment by MartiUK** [comment]
Settings > Startup > Auto save/restore opened tabs

**Comment by devsmart** [comment]
WOW!! thanks !

**Comment by ClementParis016** [comment]
I was exactly looking for this solution but it doesn't work for me :(

If I check the "auto save/restore opened tabs" option, when I restart Cmder, all tabs are set to the root drive location (in my case "Z:/"), instead of the folder they were opened in. Also, each tab lost its name and is now called as default "cmd.exe".

Is this normal?

PS: I am using Windows 8.1 with latest Cmder version.

**Comment by petersandor** [comment]
I have the same problem as @ClementParis016 and I have version 1.1.4.101.

It always follows some tasks that are somehow defined once (never actualy saving the last configuration before exit), funny thing is that I can't see these tasks on Tasks page.

![image](https://cloud.githubusercontent.com/assets/3933866/9489978/20721b3a-4be5-11e5-8102-0ced474e0767.png)

**Comment by download13** [comment]
Same problem here. I'm using Git Bash which might have something to do with it.

**Comment by aludvigsen** [comment]
Same problem here. All the tabs gets reopened, and they keep their names, but all the directories gets changed to the default directory `C:\Users\<username>\Documents`.

Any suggestions?

**Comment by azeroth2b** [comment]
My problem is worse than this... the windows and per-windows settings are never saved off.  Is this feature broken or incomplete?

**Comment by jump** [comment]
i'm also highly interested in getting this feature to work properly.

**Comment by wesamco** [comment]
i'm also highly interested in getting this feature to work properly.
 👍 1

**Comment by TommyLike** [comment]
WOW~~~~~,how nice of you guys~

**Comment by hieudang9** [comment]
Same here, please update this feature.

**Comment by TommyLike** [comment]
Settings > Startup > Auto save/restore opened tabs   @hieudang9

**Comment by Skintillion** [comment]
Profile Tabs saver would be awesome. "Save tab group as". Would be great if dealing with multiple projects.

**Comment by fleed** [comment]
`Settings > Startup > Auto save/restore opened tabs` is helpful, but I totally agree with @Skintillion: it would still be good to have the possibility to save different sets/groups of tabs to switch between contexts/projects

**Comment by Fallibilist** [comment]
If anyone previous set the default directory of Cmder by modifying the init file you'll need to remove the line you added for this feature to work correctly. That line executes after startup for each tab and changes all directories to your default directory as opposed to your previous tabs.

**Comment by oshihirii** [comment]
Is there a way to "save a workspace"?

I currently have 6 tabs saved, which is great (they all open on restart), but what happens if i start cmder, reduce tabs to 1, then close.

Will the 6 tab workspace no longer exist?

**Comment by bux23** [comment]
Saving workspaces with predefined tabs would be a really great feature

**Comment by otonielguajardo** [comment]
any news on this?

**Comment by Cobertos** [comment]
If you're using Git bash or WSL bash, it might be because Conemu cannot get the current working directory out of Git bash or WSL bash without [an extra addition to your `.bashrc`](https://conemu.github.io/en/ShellWorkDir.html#What_you_shall_do_to_get_CD_support) to update Conemu with the current directory.

[This small snippet](https://github.com/Cobertos/dotfiles/blob/master/cobertos.bashrc#L5) should work in both Git bash and WSL bash. Not sure if/why this isn't in Cmder by default

```bash
if [[ -n "${ConEmuPID}" ]]; then
  #For WSL, Sends an operating system command (OSC) to cygwin/msys connector to
  #update the cwd on PS1 print (the \w).
  #https://conemu.github.io/en/ShellWorkDir.html#connector-ps1
  PS1="\[\e]9;9;\"\w\"\007\e]9;12\007\]$PS1"
fi
if [[ ( -n "${ConEmuPID}" ) && ( -x "$(command -v ConEmuC)" ) ]]; then
  #For non-wsl, calls ConEmuC if it exists and will store cwd
  #https://conemu.github.io/en/ShellWorkDir.html#bash_and_other_cygwin_shells
  PROMPT_COMMAND="ConEmuC -StoreCWD"
fi
```

**Comment by digeomel** [comment]
This has solved the problem for me. Thank you @Cobertos ! 😄

**Comment by tdebaets** [comment]
> If you're using Git bash or WSL bash, this small snippet should work for both. It will trigger updates to `ConEmu` when those respective shells change directories. Not sure if/why this isn't in cmder by default. Add it to your `.bashrc` or equivalent file.
> 
> ```shell
> #ConEmu Integration
> if [[ -n "${ConEmuPID}" ]]; then
>   #For WSL and cygwin/msys connector (which ConEmu will use for Git bash). It
>   #sends an operating system command (OSC) to cygwin/msys connector to update the
>   #cwd on PS1 print (the \$PWD in the below string, \w will not work).
>   #https://conemu.github.io/en/ShellWorkDir.html#connector-ps1
>   #https://github.com/Maximus5/ConEmu/issues/1752
>   PS1="\[\e]9;9;\"\$PWD\"\007\e]9;12\007\]$PS1"
> fi
> ```

Even with this snippet from @Cobertos added to my `.bashrc`, restoring any tabs containing a Cygwin shell still failed on my system. When starting up ConEmu, this was displayed for each such tab:

```
Can't create new console, command execution failed

Error code: 267

<snip>

Try again with new console dialog?
```

Error code 267 is `ERROR_DIRECTORY` ("The directory name is invalid"), which pointed me to the fact that ConEmu actually saved the current directory of Cygwin shells to the `ConEmu.xml` file as a Unix-style path (e.g. `\home\tdebaets`). While the forward slashes in the path were already converted to backslashes, this obviously wasn't enough for ConEmu to find the path and was causing the errors on ConEmu startup.

I was able to fix this by adding an extra `cygpath -w` command to the `PS1` environment variable, to convert the Unix-style paths to Windows paths:

```shell
PS1="\[\e]9;9;\"\$(cygpath -w \"\$PWD\")\"\007\e]9;12\007\]$PS1"
```

**Comment by daxgames** [comment]
Not sure I understand what this actually does and what problem it solves?
