### ISSUE TITLE
Does cmder come with GCC or not?

### ISSUE THREAD

**Issue by KMelendez** [bliker/cmder#461]
I was trying out some C++ development and decided to give GCC a shot since I remembered it being included in MSysGit which was itself included in Cmder. But I can't seem to invoke the compiler. I get the not a recognized command message.

Is it included in the version of MSysGit that Cmder uses? Maybe it's not aliased or something? I'm not super familiar with command line (part of the reason I was doing this), so I could be missing something.

**Comment by MartiUK** [comment]
You may be confusing msys, a part of mingw with msysgit, msysgit only contains enough of the msys utilities to allow git to function correctly on windows. If you want to get gcc working, I suggest installing mingw and see how that goes, you may need to mess around with your PATH env variable but it should work as soon as you install it, like if you were using standard cmd.

**Comment by KMelendez** [comment]
Hmm, but the Git for Windows page says that msysgit comes with all the tools necessary to build Git on a Windows machine, notably, a port of the GCC compiler. I tried looking around the cmder directories, but I'm not sure. Does it come bundled with msysgit or just Git for Windows (without the compiler). I really just want the GCC compiler (or just a good C++ compiler, really) to be accessible through cmder. I'd rather avoid installing anything that alters my registry, PATH or anything else really.

**Comment by brendaw** [comment]
You don't understand. The parts of `msysgit` that bundles Cmder doesn't have the compilers and build things of MinGW that comes with the full `msysgit`. You only will have it when install the full `msysgit` from [their website](http://msysgit.github.io/) and adapt it to the Cmder ([see here](https://github.com/bliker/cmder/issues/183)). After install, simply add the folder `{msysgit_path}\wingw\bin` in the PATH environment variable and _voilà_.

But I suggest you install [CygWin](https://www.cygwin.com/) or [MinGW](www.mingw.org/) to develop C++ with Cmder. As you going developing, you will need a more complete solution and either of these two folks can handle it.

**Comment by KMelendez** [comment]
Thank you, that's what I was having doubts with. I thought Cmder had all of msysgit bundled with it, not just a subset of it.

I tried installing msysgit, but it runs on its own terminal window (MinGW). How would I install MinGW and then configure Cmder add GCC to its path? I thought MinGW came with its own terminal? I really rather use Cmder, and not alter registry or PATH values if I can help it.

**Comment by brendaw** [comment]
In any case, just do the tips above that will be avaible the tools in the next time you run Cmder.

PS: That's what I poorly do with CygWin :smiley:

**Comment by KMelendez** [comment]
Well, I'm downloading mingw, to see if I can get it working with that. Should it be simply making the directory visible to the PATH used by cmder? Or does it take something more involved?

Thanks for all the help, by the way. When it comes to command line interfaces, I can sometimes tread along. I don't tend to deal with them too often, though, so I can become lost sometimes. Part of the reason I want to try C++ development from the command line.

**Comment by KMelendez** [comment]
I was able to do it with MinGW, compiled a simple HelloWorld, and now ready to go. Thanks for the help, everybody.

**Comment by KingBizzleLord** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21335794/19269114/29566270-8fd6-11e6-8a6c-a85240783e46.png)
please help me with this! explain me what to do?

**Comment by daxgames** [comment]
Cmder has the complete Git for Windows which does,not have the compilers.  You probably want the Git for Windows SDK dowloadable here https://github.com/git-for-windows/build-extra/releases.  It is easier to setup and deal with than mingw.  Install it then you can integrate it into cmder.

**Comment by alwinaind** [comment]
Just download and install cygwin with all the packages you want, and copy all the files in the bin folder of cygwin,  in the bin folder of cmder.
