### ISSUE TITLE
mklink /d creates symlink with wrong slashes

### ISSUE THREAD

**Issue by mikesigs** [bliker/cmder#462]
This is a bit of an odd one. Here are the steps to reproduce the issue, and steps for a work around. Switch with your own local paths of course.

In Cmder, create a symbolic link to a directory: 
`mklink /d c:\blog c:\source\github\mikesigs.github.io`

Now, using [Brackets](http://brackets.io/) run the command `brackets c:\blog`

Brackets opens up, and the Brackets Git plugin reports the error "Invalid symlink c:/blog". Notice the forward slash in the error message. At first I thought this must be a bug with the plugin, but read on to see why I don't think that is actually the issue.

To demonstrate the problem might in fact be with Cmder (or Conemu) delete the symlink we just created: `rmdir c:\blog`. Now open up a regular `cmd` as Admin and run the mklink command again:
`mklink /d c:\blog c:\source\github\mikesigs.github.io` 
Now open the folder in Brackets again: `brackets c:\blog`. This time, there is no error message reported by the Brackets Git plugin.

What could be going on here? Obviously it has something to do with msysgit, and how it swap slashes, but beyond that... I got nuthin.

Anyways, I have a work around so this isn't urgent (i.e. create symlinks using Windows cmd). But I figured I'd report the issue anyways.

**Comment by mikesigs** [comment]
Okay, so apparently this is a known issue with Git itself and windows symlinks. The best solution is to use a junction instead of a symlink. So intead of `mklink /d` use `mklink /j` instead.

[Moar info](https://github.com/msysgit/msysgit/wiki/Why-am-I-getting-fatal-Invalid-symlink-....-Function-not-supported.-error-when-initcloneing)

**Comment by cyrilcourtney** [comment]
Hello,
I just discovered cmder and got the same problem. It has however nothing to deal with Git.
When executed under cmder mklink produces rubbish. Same commands executed under cmd or tccle (from jpsoft) work like a charm.
Curious to know if 5 years later this would be fixed or shared by others.
All the best.
