### ISSUE TITLE
Missing MSVCP140.dll

### ISSUE THREAD

**Issue by RyenNelsen** [bliker/cmder#480]
I have all the up-to-date C++ Redistributable Packages installed, but I am getting the following error:
![2015-05-17 17_33_53-cmder exe - system error](https://cloud.githubusercontent.com/assets/10788652/7672938/104d6972-fcbb-11e4-91d9-d8348f239c06.png)

The previous version of Cmder was running fine, though the newest release is not.

**Comment by tyler-herman** [comment]
Do you have the 2015 Redistributable packages?  Looks like it uses those.  You can download them from https://www.microsoft.com/en-us/download/details.aspx?id=46881.

**Comment by RyenNelsen** [comment]
That did it, apparently I didn't have the 32bit 2015.
