### ISSUE TITLE
Symantec Risk Found

### ISSUE THREAD

**Issue by szwchao** [bliker/cmder#481]
![2015-05-18 09_37_44-symantec endpoint protection notification](https://cloud.githubusercontent.com/assets/2680520/7673231/a2e7d304-fd41-11e4-9f3e-72371a7b7392.png)
Symantec just found this risk issue with latest cmder version 1.2. But there is no such notification from Symantec when I use v1.1.4.

**Comment by EirikV** [comment]
I'm experiencing the same thing with Symantec with the latest version of cmder.

**Comment by MartiUK** [comment]
Sorry, the only thing I can suggest is to set cmder as a trusted executable or something like that.

**Comment by eliashdezr** [comment]
Yeah, I got this error too.

**Comment by RNiK** [comment]
I've submitted the false positive trough Symantec Reporting Tool ==> https://submit.symantec.com/false_positive/
I think it would be useful if cmder author and the others cmder users report it too.

**Comment by erikhakansson** [comment]
I submitted a false positive report a few hours ago and got the response that the false positive has been confirmed. Cmder will be added to the whitelist in the next 24 hours.

**Comment by MartiUK** [comment]
Thanks @RNiK and @erikhakansson for sending the reports.
