### ISSUE TITLE
Symantec refuses to access cmder

### ISSUE THREAD

**Issue by burakmetehan** [bliker/cmder#484]
Symantec antivirus refuses to extract zip archive and access to cmder (Suspicous executable). Just to let you know.

**Comment by NicoPennec** [comment]
same issue

Symantec Report:
> Scan type: Auto-Protect Scan
> Event: Security Risk Found!
> Security risk detected: Suspicious.Mystic
> File: C:\cmder\Cmder.exe
> Location: Deleted or access blocked

**Comment by NicoPennec** [comment]
duplicate issue #481
