### ISSUE TITLE
about_Execution_Policies

### ISSUE THREAD

**Issue by ezekielvdp** [bliker/cmder#489]
![screenshot_1](https://cloud.githubusercontent.com/assets/8132670/7694814/4210c432-fe18-11e4-9063-1d2c4ff7b84d.png)

I need help on this one! Cannot find a solution for this problem!

**Comment by Stanzilla** [comment]
duplicate of https://github.com/bliker/cmder/issues/483

**Comment by MartiUK** [comment]
See #483.
