### ISSUE TITLE
{hg} on every folder

### ISSUE THREAD

**Issue by Stanzilla** [bliker/cmder#494]
After https://github.com/utek/cmder/commit/8a885167c3d5cab6833e30ffb2c6abd80af582fb you now have {hg} visible on every folder, this comes from registering the hg filter in the git.lua file (why even? o.o) 

Also after https://github.com/bliker/cmder/commit/b75b3239e7b9d74a83f7eafa9d34fb6a3a63bbbb and the inclusion of `clink-completions` we now have git handled twice, once in `clink-completions` and once in `cmder.lua`, so one of those has to be altered so we don't have git support twice.

**Comment by MartiUK** [comment]
clink-completions only affects the completions, the replacement of {git} is handled in cmder.lua.

For why you're seeing {hg} I don't know, I'm running W7 SP1 and I can't see {hg} at all, did you overwrite an older version?

**Comment by Stanzilla** [comment]
Eh, right. That's how it ends up with the extra git.lua file. Probably makes sense to mention this somewhere that people who upgrade have to delete those files.

**Comment by strebl** [comment]
@Stanzilla I can confirm. {hg} gone after I deleted git.lua and prompt.lua.
