### ISSUE TITLE
cannot run cmder

### ISSUE THREAD

**Issue by ittayd** [bliker/cmder#516]
I get the following dialog:
---------------------------
Cmder.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

**Comment by NicolasParada** [comment]
Same here :(

**Comment by husa** [comment]
duplicate of #501
