### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll error

### ISSUE THREAD

**Issue by rahlzel** [bliker/cmder#518]
I've seen both "duplicates" (#490 and #482) but this seems to be a bigger problem.

Downloading the C++ redistributables [from Windows](https://www.microsoft.com/en-US/download/details.aspx?id=46881) isn't working. I've tried Chrome, Firefox, and I've tried Incognito mode for both in order to disable extensions in case they're the culprit.

So at the moment, my guess is that anyone without those redistributables can no longer use the latest version of Cmder, including myself.

A fix could include providing the needed installer files in a /redist folder of some kind. That would be a big help. I need to downgrade to the last release of Cmder in order to get it working.

**Comment by MartiUK** [comment]
Will be fixed in the next release, C++ re-distributable dlls will be included.

**Comment by rotatingJazz** [comment]
+1

**Comment by suenot** [comment]
:+1:
