### ISSUE TITLE
api-ms-win-crt-runtime l1-109.dll is missing

### ISSUE THREAD

**Issue by alexlaw17** [bliker/cmder#531]
After I updated my windows 8.1 cmder stopped working. A pop up appears saying, "api-ms-win-crt-runtime l1-109.dll is missing." How can I fix this?

![image](https://cloud.githubusercontent.com/assets/6556934/8117223/9cfaca16-1054-11e5-873f-30e37cde61b9.png)

**Comment by hamdani100** [comment]
solved here
https://github.com/bliker/cmder/issues/501#issuecomment-104749350

**Comment by alexlaw17** [comment]
nice thanks!

**Comment by matteocontrini** [comment]
Close this issues as there's another one
