### ISSUE TITLE
How to use cmder in a batch file?

### ISSUE THREAD

**Issue by rotatingJazz** [bliker/cmder#556]
I want to run a bat file from within cmder (colors, yay!). Instead of opening cmder and starting the bat file from there, I want to double click the bat file on explorer and have its content (one line) piped into cmder (I have {cmd} as default on startup). Is this possible?

**Comment by Maximus5** [comment]
1. Put xml in `conemu-maximus5` folder. Use `mklink` for example. BTW, I completely can't understand why Samuel chose to store xml outside of standard paths. May be to make ConEmu unusable standalone?

2. http://conemu.github.io/en/DefaultTerminal.html

**Comment by rotatingJazz** [comment]
Thank you very much! :+1: :beer:
