### ISSUE TITLE
git add --interactive fails

### ISSUE THREAD

**Issue by withinboredom** [bliker/cmder#560]
Doing `git add -up` fails in an interesting way:

`git: 'add--interactive' is not a git command. See 'git --help'.`

**Comment by withinboredom** [comment]
I should also add that `git rebase` fails as well...

`git: 'rebase' is not a git command. See 'git --help'.`

**Comment by glucas** [comment]
I suspect this is the same issue as #521.

**Comment by withinboredom** [comment]
Dupe of #521
