### ISSUE TITLE
Persist tab "View (palette)" selection

### ISSUE THREAD

**Issue by hekar** [bliker/cmder#562]
Opening a new tab defaults to the "Monokai" theme. You can change the theme for a particular tab, but where do you set the default palette option?

Right click on tab -> "View (palettes)"
![http://i.imgur.com/TCS7ioq.png](http://i.imgur.com/TCS7ioq.png)

Looking in ConEmu.xml, I can see the palette definition for "Monokai"
![http://i.imgur.com/bCXLd1h.png](http://i.imgur.com/bCXLd1h.png)

How would I change this to "Solarized" (without setting each value manually?)

**Comment by kermage** [comment]
Change default **Schemes** in **`Settings` > `Features` > `Colors`**

**Comment by hekar** [comment]
Thanks! Not sure how I didn't see that.
