### ISSUE TITLE
Misleading install instructions?

### ISSUE THREAD

**Issue by antoniobrandao** [bliker/cmder#588]
Why are the instructions like this:

Installation:
- Unzip (can take a while)
- (optional) Place your own executable files into the bin folder to be injected into your PATH.
- Run Cmder (Cmder.exe)

If every time I follow these steps to install Cmder in a fresh Windows machine, I always get the error:

"The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing form your computer"

And then we have to search the Internetz to find dozens of issues in this repo explaining one must first install huge stuff from Microsoft (Visual C++ Redistributable for Visual Studio 2015).

Would help a bit to clarify this in the Cmder instructions.

**Comment by Stanzilla** [comment]
No need to make dozens more tickets about it. It's a known problem.

**Comment by Stanzilla** [comment]
You can download a fixed version here btw https://github.com/Stanzilla/cmder/releases/tag/v1.2.1

**Comment by antoniobrandao** [comment]
Thanks!! That totally saved my day.
