### ISSUE TITLE
PowerShell Profile Aliases ignored in Cmder

### ISSUE THREAD

**Issue by Francisc** [bliker/cmder#593]
Hello,

I have a few aliases set in my Profile.ps1 file.
They work when starting powershell.exe but fail when using PowerShell in cmder.

Is there any way to make them work in cmder?
Thanks.

**Comment by LeoColomb** [comment]
In settings, go to Tasks, then remove ` -NoProfile`.
You can also search `-NoProfile` in settings then remove it where you can.

**Comment by Francisc** [comment]
Thanks. Does that have any side-effects for cmder itself?
Or does it simply allow profiles to be loaded?

**Comment by LeoColomb** [comment]
> Does that have any side-effects for cmder itself?

Possibly. Longer to load, that's all.

**Comment by Francisc** [comment]
If that's all, it's fine. I actually saw and removed that a few days ago and performance didn't drop at all, at least not noticeably.

Thank you, Leo.
