### ISSUE TITLE
Resizing split windows

### ISSUE THREAD

**Issue by jonnymaceachern** [bliker/cmder#596]
Is it possible to drag/resize split windows? Right now I'm only able to split the current tab by half, so 50/50, then 25/25/50, etc.

**Comment by glucas** [comment]
Yes. Open the Settings window and navigate to `Keys & Macro`. In the list of key bindings you will find a number of keys for working with split windows, prefixed with "Split: ". 

What you are looking for is "Split: Move splitter downward" and related keys for moving the splitter in all directions. You can try the default key bindings or edit to set your own keys.

**Comment by jonnymaceachern** [comment]
Awesome, thanks
