### ISSUE TITLE
Prevent inactive cmder windows to be dimmed

### ISSUE THREAD

**Issue by mekf** [bliker/cmder#603]
hi guys,

Navigating away from the cmder window makes it becoming inactive and the whole window got slightly dimmer. I found this quite distracting. Is there a setting to change this behaviour.

Regards,
Minh

**Comment by r3Fuze** [comment]
Head into the ConEmu settings and then under `Features` you'll find `Transparency`. Then you can untick the box for separate transparency for inactive window. You can also completely turn off transparency if you find that distracting.

**Comment by 0xack13** [comment]
ConEmu settings -> `Features` -> `Colors` -> uncheck `Fade when inactive` in the `Graphic enhancement` groupbox.

**Comment by mekf** [comment]
> ConEmu settings -> Features -> Colors -> uncheck Fade when inactive in the Graphic enhancement groupbox.

@0xack13 thank you. this works

**Comment by brooth** [comment]
> ConEmu settings -> Features -> Colors -> uncheck Fade when inactive in the Graphic enhancement groupbox.
Thanks, that's a really annoing feature

**Comment by TheNexusDesigns** [comment]
> ConEmu settings -> Features -> Colors -> uncheck Fade when inactive in the Graphic enhancement groupbox.

Thanks so much yeah this was so annoying with that fade effects, so glad that we can disable it :+1:

**Comment by bertoost** [comment]
Indeed annoying.. since there is already a transparency feature too

**Comment by jbaranski** [comment]
This should be turned off by default. Extremely annoying.
